services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: owl
      POSTGRES_PASSWORD: owl
      POSTGRES_DB: owl
    ports:
      - "5432:5432"
    volumes:
      - owl-pg:/var/lib/postgresql/data

volumes:
  owl-pg:
